version: '3.8'
services:
  web_blog:
    container_name: web-blog
    build:
      context: ./services/web-blog
      dockerfile: Dockerfile
    ports:
      - 3069:3069
    volumes:
      - ./services/web-blog/:/go/src/app/
  db:
    container_name: db
    build: 
      context: ./services/db
      dockerfile: Dockerfile
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
  dbadmin:
    container_name: db-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root
    ports: 
      - "5051:80"

